/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class AddressChangeRequestMetadataView extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "can_change_shipping_address" })
    canChangeShippingAddress?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "ticket_id" })
    ticketId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "ticket_status" })
    ticketStatus?: string;
}
