/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AddressView } from "./addressview";
import { Expose, Type } from "class-transformer";

export class AddressChangeView extends SpeakeasyBase {
    /**
     * The address object returned in the response.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "from_address" })
    @Type(() => AddressView)
    fromAddress?: AddressView;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "ticket_id" })
    ticketId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "timestamp" })
    timestamp?: number;

    /**
     * The address object returned in the response.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "to_address" })
    @Type(() => AddressView)
    toAddress?: AddressView;
}
