/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Metadata } from "./metadata";
import { Expose, Type } from "class-transformer";

/**
 * The Address object is used for billing, shipping, and physical store address use cases.
 */
export class AddressAccount extends SpeakeasyBase {
    /**
     * The company name associated with this address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "company" })
    company?: string;

    /**
     * The name of the country associated with this address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "country" })
    country?: string;

    /**
     * The ISO 3166-1 alpha-2 country code associated with this address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "country_code" })
    countryCode: string;

    /**
     * Set this to true to make this the default shipping address. There can be only one address with default set to true.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "default" })
    default?: boolean;

    /**
     * The building door code or community gate code.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "door_code" })
    doorCode?: string;

    /**
     * An email address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "email" })
    email: string;

    /**
     * The given name of the person associated with this address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "first_name" })
    firstName: string;

    /**
     * The surname of the person associated with this address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "last_name" })
    lastName: string;

    /**
     * The city name details associated with this address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "locality" })
    locality: string;

    /**
     * A key-value pair object that allows users to store arbitrary information associated with an object.  For any individual account object, we allow up to 50 keys. Keys can be up to 40 characters long and values can be up to 500 characters long.  Metadata should not contain any sensitive customer information, like PII (Personally Identifiable Information). For more information about metadata, see our [documentation](https://help.bolt.com/developers/references/embedded-metadata/).
     *
     * @remarks
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "metadata" })
    @Type(() => Metadata)
    metadata?: Metadata;

    /**
     * The given and surname of the person associated with this address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    /**
     * A phone number following E164 standards, in its globalized format, i.e. prepended with a plus sign.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "phone" })
    phone?: string;

    /**
     * The the postal or zip code associated with this address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "postal_code" })
    postalCode: string;

    /**
     * **Not Required for NON US addresses**. The region details such as state or province associated with this address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "region" })
    region: string;

    /**
     * The ISO 3166-2 region code associated with this address.
     *
     * @remarks
     *   - * If specified, value must be valid for the `country`.
     *   - * If null, value is inferred from the `region`.
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "region_code" })
    regionCode?: string;

    /**
     * The street number and street name of the address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "street_address1" })
    streetAddress1: string;

    /**
     * Any apartment, floor, or unit details.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "street_address2" })
    streetAddress2?: string;

    /**
     * Any additional street address details.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "street_address3" })
    streetAddress3?: string;

    /**
     * Any additional street address details.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "street_address4" })
    streetAddress4?: string;
}
