/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * The amount. **Nullable** for Transactions Details.
 */
export class Amounts extends SpeakeasyBase {
    /**
     * The amount in cents. **Nullable** for Transactions Details.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "amount" })
    amount: number;

    /**
     * The 3-digit ISO code for the currency. **Nullable** for Transactions Details.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "currency" })
    currency: string;

    /**
     * The currency symbol used for the amount. **Nullable** for Transactions Details.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "currency_symbol" })
    currencySymbol: string;
}
