/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Used to track the status of micro-authorizations. **Nullable** for Transactions Details.
 */
export enum AuthorizationVerificationStatus {
    New = "new",
    Verified = "verified",
    Failed = "failed",
    Expired = "expired",
}
