/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The status of the capture. **Nullable** for Transactions Details.
 */
export enum CaptureStatus {
    Succeeded = "succeeded",
    Declined = "declined",
    Error = "error",
}
