/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The card's network. **Nullable** for Transactions Details.
 */
export enum CardDisplayNetwork {
    CreditCard = "Credit Card",
    AmericanExpress = "American Express",
    DinersClub = "Diners Club",
    Discover = "Discover",
    Jcb = "JCB",
    MasterCard = "MasterCard",
    UnionPay = "Union Pay",
    Visa = "Visa",
}
