/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The card's status. **Nullable** for Transactions Details.
 */
export enum CardStatus {
    Active = "active",
    Created = "created",
    Inactive = "inactive",
    Transient = "transient",
}
