/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Used to define which payment processor generated the token for this credit card.
 *
 * @remarks
 *
 */
export enum CardTokenType {
    Vantiv = "vantiv",
    Applepay = "applepay",
    Bolt = "bolt",
    Stripe = "stripe",
    Plcc = "plcc",
    ApplepayEncryptedBlob = "applepay_encrypted_blob",
}
