/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class CartItemProperty extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "color" })
    color?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "display" })
    display?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "name_id" })
    nameId?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "value" })
    value?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "value_id" })
    valueId?: number;
}
