/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AddressView } from "./addressview";
import { AmountView } from "./amountview";
import { ICartDiscountView } from "./icartdiscountview";
import { ICartItemView } from "./icartitemview";
import { ICartShipmentView } from "./icartshipmentview";
import { ICurrency } from "./icurrency";
import { InStoreShipment2 } from "./instoreshipment2";
import { Expose, Type } from "class-transformer";

export class CartViewFulfillments extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "cart_shipment" })
    @Type(() => ICartShipmentView)
    cartShipment?: ICartShipmentView;

    @SpeakeasyMetadata()
    @Expose({ name: "fulfillment_type" })
    fulfillmentType?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * A cart that is being prepared for shipment
     */
    @SpeakeasyMetadata()
    @Expose({ name: "in_store_cart_shipment" })
    @Type(() => InStoreShipment2)
    inStoreCartShipment?: InStoreShipment2;

    @SpeakeasyMetadata({ elemType: ICartItemView })
    @Expose({ name: "items" })
    @Type(() => ICartItemView)
    items?: ICartItemView[];
}

export class CartViewLoyaltyRewards extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "amount" })
    @Type(() => AmountView)
    amount?: AmountView;

    @SpeakeasyMetadata()
    @Expose({ name: "coupon_code" })
    couponCode?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "details" })
    details?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "points" })
    points?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "source" })
    source?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: string;
}

/**
 * This is the cart object returned in a successful response.
 */
export class CartView extends SpeakeasyBase {
    /**
     * The address object returned in the response.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "billing_address" })
    @Type(() => AddressView)
    billingAddress?: AddressView;

    /**
     * Used to provide a link to the cart ID.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "cart_url" })
    cartUrl?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "currency" })
    @Type(() => ICurrency)
    currency?: ICurrency;

    @SpeakeasyMetadata()
    @Expose({ name: "discount_amount" })
    @Type(() => AmountView)
    discountAmount?: AmountView;

    @SpeakeasyMetadata({ elemType: ICartDiscountView })
    @Expose({ name: "discounts" })
    @Type(() => ICartDiscountView)
    discounts?: ICartDiscountView[];

    @SpeakeasyMetadata()
    @Expose({ name: "display_id" })
    displayId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "fee_amount" })
    @Type(() => AmountView)
    feeAmount?: AmountView;

    @SpeakeasyMetadata({ elemType: ICartItemView })
    @Expose({ name: "fees" })
    @Type(() => ICartItemView)
    fees?: ICartItemView[];

    @SpeakeasyMetadata({ elemType: CartViewFulfillments })
    @Expose({ name: "fulfillments" })
    @Type(() => CartViewFulfillments)
    fulfillments?: CartViewFulfillments[];

    /**
     * A cart that is being prepared for shipment
     */
    @SpeakeasyMetadata()
    @Expose({ name: "in_store_shipments" })
    @Type(() => InStoreShipment2)
    inStoreShipments?: InStoreShipment2;

    @SpeakeasyMetadata({ elemType: ICartItemView })
    @Expose({ name: "items" })
    @Type(() => ICartItemView)
    items?: ICartItemView[];

    @SpeakeasyMetadata({ elemType: CartViewLoyaltyRewards })
    @Expose({ name: "loyalty_rewards" })
    @Type(() => CartViewLoyaltyRewards)
    loyaltyRewards?: CartViewLoyaltyRewards[];

    @SpeakeasyMetadata()
    @Expose({ name: "loyalty_rewards_amount" })
    @Type(() => AmountView)
    loyaltyRewardsAmount?: AmountView;

    @SpeakeasyMetadata()
    @Expose({ name: "merchant_order_url" })
    merchantOrderUrl?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "metadata" })
    metadata?: Record<string, string>;

    @SpeakeasyMetadata()
    @Expose({ name: "msrp" })
    @Type(() => AmountView)
    msrp?: AmountView;

    /**
     * Used optionally to pass additional information like order numbers or other IDs as needed.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "order_description" })
    orderDescription?: string;

    /**
     * This value is used by Bolt as an external reference to a given order. This reference must be unique per successful transaction.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "order_reference" })
    orderReference?: string;

    @SpeakeasyMetadata({ elemType: ICartShipmentView })
    @Expose({ name: "shipments" })
    @Type(() => ICartShipmentView)
    shipments?: ICartShipmentView[];

    @SpeakeasyMetadata()
    @Expose({ name: "shipping_amount" })
    @Type(() => AmountView)
    shippingAmount?: AmountView;

    @SpeakeasyMetadata()
    @Expose({ name: "subtotal_amount" })
    @Type(() => AmountView)
    subtotalAmount?: AmountView;

    @SpeakeasyMetadata()
    @Expose({ name: "tax_amount" })
    @Type(() => AmountView)
    taxAmount?: AmountView;

    @SpeakeasyMetadata()
    @Expose({ name: "total_amount" })
    @Type(() => AmountView)
    totalAmount?: AmountView;

    /**
     * The 12 digit reference ID associated to a given transaction webhook for an order.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "transaction_reference" })
    transactionReference?: string;
}
