/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * A list of up to 3 add-ons that are displayed to the shopper.
 */
export class CartAddOn extends SpeakeasyBase {
    /**
     * The description of the product being displayed as an add on.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description?: string;

    /**
     * The URL of the image displayed for the add on product.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "imageUrl" })
    imageUrl?: string;

    /**
     * The name of the product being displayed as an add on.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    /**
     * The price of the product add on in cents (1/100).
     */
    @SpeakeasyMetadata()
    @Expose({ name: "price" })
    price: number;

    /**
     * The the ID of the product being displayed as an add on.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "productId" })
    productId: string;

    /**
     * The URL to the product page of the product being displayed as an add on.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "productPageUrl" })
    productPageUrl?: string;
}
