/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Address } from "./address";
import { CartShipmentType } from "./cartshipmenttype";
import { Expose, Type } from "class-transformer";

/**
 * A cart that is being prepared for shipment
 */
export class CartShipment extends SpeakeasyBase {
    /**
     * The name of the carrier selected.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "carrier" })
    carrier?: string;

    /**
     * The cost in cents.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "cost" })
    cost?: number;

    /**
     * Defines if shopper has a membership discount.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "discounted_by_membership" })
    discountedByMembership?: boolean;

    /**
     * The estimated delivery date.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "estimated_delivery_date" })
    estimatedDeliveryDate?: string;

    /**
     * True if shipment is expedited.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "expedited" })
    expedited?: boolean;

    /**
     * The depth.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "package_depth" })
    packageDepth?: number;

    /**
     * The unit of measurement for an item's dimensions.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "package_dimension_unit" })
    packageDimensionUnit?: string;

    /**
     * The height.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "package_height" })
    packageHeight?: number;

    /**
     * The type of package.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "package_type" })
    packageType?: string;

    /**
     * The unit of measurement for an item's weight.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "package_weight_unit" })
    packageWeightUnit?: string;

    /**
     * The width.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "package_width" })
    packageWidth?: number;

    /**
     * The service name.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "service" })
    service?: string;

    /**
     * The Address object is used for billing, shipping, and physical store address use cases.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "shipping_address" })
    @Type(() => Address)
    shippingAddress?: Address;

    /**
     * ID for billing address
     */
    @SpeakeasyMetadata()
    @Expose({ name: "shipping_address_id" })
    shippingAddressId?: string;

    /**
     * The name of the shipping method.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "shipping_method" })
    shippingMethod?: string;

    /**
     * The signature.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "signature" })
    signature?: string;

    /**
     * Tax amount in cents.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "tax_amount" })
    taxAmount?: number;

    /**
     * The relevant tax code.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "tax_code" })
    taxCode?: string;

    /**
     * The total weight.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "total_weight" })
    totalWeight?: number;

    /**
     * The unit of measurement for an item's weight.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "total_weight_unit" })
    totalWeightUnit?: string;

    /**
     * The type corresponding to this shipment, if applicable.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: CartShipmentType;
}
