/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The type corresponding to this shipment, if applicable.
 */
export enum CartShipmentType {
    DoorDelivery = "door_delivery",
    InStorePickup = "in_store_pickup",
    ShipToStore = "ship_to_store",
    ShipToHomeOnly = "ship_to_home_only",
    Unknown = "unknown",
}
