/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The result of the chargeback representment.
 */
export enum ChargebackRepresentmentResult {
    None = "none",
    Open = "open",
    Lost = "lost",
    Won = "won",
}
