/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ConsumerMembershipStatus } from "./consumermembershipstatus";
import { Expose } from "class-transformer";

/**
 * **Nullable** for Transactions Details.
 *
 * @remarks
 *
 */
export class ConsumerUserMembership extends SpeakeasyBase {
    /**
     * True if user has an AllPass membership associated to their Bolt Account. **Nullable** for Transactions Details.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status: ConsumerMembershipStatus;
}
