/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * True if user has an AllPass membership associated to their Bolt Account. **Nullable** for Transactions Details.
 */
export enum ConsumerMembershipStatus {
    Active = "active",
    Cancelled = "cancelled",
    Disabled = "disabled",
    FreeTrial = "free_trial",
}
