/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * The status of the refund to a card.
 */
export enum CreditCardCreditViewStatus {
    Succeeded = "succeeded",
    Declined = "declined",
    Error = "error",
    Pending = "pending",
    InProgress = "in progress",
}

export class CreditCardCreditView extends SpeakeasyBase {
    /**
     * The reference ID associated with a transaction event (auth, capture, refund, void). This is an arbitrary identifier created by the merchant. Bolt does not enforce any uniqueness constraints on this ID. It is up to the merchant to generate identifiers that properly fulfill its needs.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "merchant_event_id" })
    merchantEventId?: string;

    /**
     * The status of the refund to a card.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: CreditCardCreditViewStatus;
}
