/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Address } from "./address";
import { Expose, Type } from "class-transformer";

/**
 * Used to indicate the card's priority. '1' indicates primary, while '2' indicates a secondary card.
 */
export enum CreditCardPriority {
    One = 1,
    Two = 2,
}

/**
 * Used to define which payment processor generated the token for this credit card; for those using Bolt's tokenizer, the value must be `bolt`.
 */
export enum CreditCardTokenType {
    Bolt = "bolt",
}

/**
 * The credit_card object is used to to pay for guest-checkout transactions or save payment method details to an account. Once saved, you can reference the credit card with the associated `credit_card_id` for future transactions. Add `billing_address` to this if storing a billing address for a returning shopper.
 */
export class CreditCard extends SpeakeasyBase {
    /**
     * The Address object is used for billing, shipping, and physical store address use cases.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "billing_address" })
    @Type(() => Address)
    billingAddress?: Address;

    /**
     * The Bank Identification Number for the credit card; this is typically the first 4-6 digits of the credit card number.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "bin" })
    bin: string;

    /**
     * The expiration date of the credit card.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "expiration" })
    expiration: string;

    /**
     * The last 4 digits of the credit card number.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "last4" })
    last4: string;

    /**
     * Used for the postal or zip code associated with the credit card.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "postal_code" })
    postalCode: string;

    /**
     * Used to indicate the card's priority. '1' indicates primary, while '2' indicates a secondary card.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "priority" })
    priority?: CreditCardPriority;

    /**
     * Determines whether or not the credit card will be saved to the shopper's account. Defaults to `true`.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "save" })
    save?: boolean;

    /**
     * The Bolt token associated to the credit card.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "token" })
    token: string;

    /**
     * Used to define which payment processor generated the token for this credit card; for those using Bolt's tokenizer, the value must be `bolt`.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "token_type" })
    tokenType: CreditCardTokenType;
}
