/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Emails } from "./emails";
import { PhonesWithCountryCode } from "./phoneswithcountrycode";
import { Expose, Type } from "class-transformer";

/**
 * The credit card user.
 */
export class CreditCardUser extends SpeakeasyBase {
    /**
     * A list of email addresses. **Nullable** for Transactions Details.
     */
    @SpeakeasyMetadata({ elemType: Emails })
    @Expose({ name: "emails" })
    @Type(() => Emails)
    emails?: Emails[];

    /**
     * The person's first name.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "first_name" })
    firstName?: string;

    /**
     * The shopper's unique ID.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * The person's last name.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "last_name" })
    lastName?: string;

    /**
     * A list of phone numbers.
     */
    @SpeakeasyMetadata({ elemType: PhonesWithCountryCode })
    @Expose({ name: "phones" })
    @Type(() => PhonesWithCountryCode)
    phones?: PhonesWithCountryCode[];
}
