/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AddressView } from "./addressview";
import { CardDisplayNetwork } from "./carddisplaynetwork";
import { CardNetwork } from "./cardnetwork";
import { CardStatus } from "./cardstatus";
import { CardTokenType } from "./cardtokentype";
import { Priority } from "./priority";
import { Expose, Type } from "class-transformer";

/**
 * Contains details about the credit card transaction.
 */
export class CreditCardView extends SpeakeasyBase {
    /**
     * The address object returned in the response.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "billing_address" })
    @Type(() => AddressView)
    billingAddress?: AddressView;

    /**
     * The Bank Identification Number for the credit card; this is typically the first 4-6 digits of the credit card number. **Nullable** for Transactions Details.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "bin" })
    bin?: string;

    /**
     * The card's network. **Nullable** for Transactions Details.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "display_network" })
    displayNetwork?: CardDisplayNetwork;

    /**
     * The card's expiration. **Nullable** for Transactions Details.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "expiration" })
    expiration?: number;

    /**
     * The asset link for displayed icons. This link varies depending on payment method used.  **Nullable** for Transactions Details.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "icon_asset_path" })
    iconAssetPath?: string;

    /**
     * The card's ID. **Nullable** for Transactions Details.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * The card's last 4 digits. **Nullable** for Transactions Details.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "last4" })
    last4?: string;

    /**
     * The card's network code. **Nullable** for Transactions Details. Note: LEGACY diners_club_us_ca now tagged as mastercard
     *
     * @remarks
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "network" })
    network?: CardNetwork;

    /**
     * Describes the card's priority.
     *
     * @remarks
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "priority" })
    priority?: Priority;

    /**
     * The card's status. **Nullable** for Transactions Details.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: CardStatus;

    /**
     * The Bolt token associated to the credit card. Required for new, unsaved cards.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "token" })
    token?: string;

    /**
     * Used to define which payment processor generated the token for this credit card.
     *
     * @remarks
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "token_type" })
    tokenType?: CardTokenType;
}
