/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The status of the authorization request.
 *
 * @remarks
 *   * `1` - succeeded
 *   * `2` - declined
 *   * `3` - error
 *
 */
export enum CreditCardAuthorizationStatus {
    Succeeded = "succeeded",
    Declined = "declined",
    Error = "error",
}
