/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum CheckoutSetup {
    ShippingStep = "shipping_step",
    DeliveryStep = "delivery_step",
    PaymentStep = "payment_step",
    AccountRegistrationSso = "account_registration_sso",
}

export class CustomFields extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "checkout_setup" })
    checkoutSetup?: CheckoutSetup;

    /**
     * Defines whether the field is dynamic.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "dynamic" })
    dynamic?: boolean;

    /**
     * The external ID for the custom field.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "external_id" })
    externalId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "field_setup" })
    fieldSetup?: string;

    /**
     * The displayed label for the custom field, seen by the shopper.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "label" })
    label?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "position" })
    position?: number;

    /**
     * The internal ID for the custom field.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "public_id" })
    publicId?: string;

    /**
     * Defines if the field must be completed to check out.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "required" })
    required?: boolean;

    /**
     * Defines whether the shopper is opted into a newsletter or not.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "subscribe_to_newsletter" })
    subscribeToNewsletter?: boolean;
}
