/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * This is the status of the contact method.
 */
export enum EmailStatus {
    Active = "active",
    Pending = "pending",
    Inactive = "inactive",
}
