/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Contains the gift option settings for wrapping and custom messages.
 */
export class GiftOptions extends SpeakeasyBase {
    /**
     * Includes the gift message written by the shopper.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    message?: string;

    /**
     * Defines whether gift wrapping was requested.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "wrap" })
    wrap?: boolean;
}
