/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { TransactionView } from "./transactionview";
import { Expose, Type } from "class-transformer";

export class IAuthorizeResultView extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "did_create_bolt_account" })
    didCreateBoltAccount?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "order_number" })
    orderNumber?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "transaction" })
    @Type(() => TransactionView)
    transaction?: TransactionView;
}
