/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AmountView } from "./amountview";
import { IFreeShippingDiscountView } from "./ifreeshippingdiscountview";
import { Expose, Type } from "class-transformer";

export enum ICartDiscountViewDiscountCategory {
    Coupon = "coupon",
    Giftcard = "giftcard",
    ManagedGiftcard = "managed_giftcard",
    StoreCredit = "store_credit",
    AutomaticPromotion = "automatic_promotion",
    MembershipDiscount = "membership_discount",
    MembershipGiftcard = "membership_giftcard",
    SubscriptionDiscount = "subscription_discount",
    RewardsDiscount = "rewards_discount",
    Unknown = "unknown",
}

export class ICartDiscountView extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "amount" })
    @Type(() => AmountView)
    amount?: AmountView;

    /**
     * Discount code used.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "code" })
    code?: string;

    /**
     * Used to define the discount offering.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description?: string;

    /**
     * Used to provide a link to additional details, such as a landing page, associated with the discount offering.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "details_url" })
    detailsUrl?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "discount_category" })
    discountCategory?: ICartDiscountViewDiscountCategory;

    @SpeakeasyMetadata()
    @Expose({ name: "free_shipping" })
    @Type(() => IFreeShippingDiscountView)
    freeShipping?: IFreeShippingDiscountView;

    /**
     * Used to define the reference ID associated with the discount available.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "reference" })
    reference?: string;
}
