/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class ICartItemExternalInputs extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "shopify_line_item_reference" })
    shopifyLineItemReference?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "shopify_product_reference" })
    shopifyProductReference?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "shopify_product_variant_reference" })
    shopifyProductVariantReference?: number;
}
