/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum CheckoutStep {
    ShippingStep = "SHIPPING_STEP",
    DeliveryStep = "DELIVERY_STEP",
    PaymentStep = "PAYMENT_STEP",
    AccountRegistrationSso = "ACCOUNT_REGISTRATION_SSO",
}

export class ICustomFieldView extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "checkout_step" })
    checkoutStep?: CheckoutStep;

    @SpeakeasyMetadata()
    @Expose({ name: "dynamic" })
    dynamic?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "external_id" })
    externalId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "field_setup" })
    fieldSetup?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "helper_text" })
    helperText?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "label" })
    label?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "position" })
    position?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "public_id" })
    publicId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "required" })
    required?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "subscribeToNewsletter" })
    subscribeToNewsletter?: boolean;
}
