/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class IGiftOptionView extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "hide_gift_message" })
    hideGiftMessage?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "hide_gift_wrap" })
    hideGiftWrap?: boolean;
}
