/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Amounts } from "./amounts";
import { ConsumerBillingAddress } from "./consumerbillingaddress";
import { GiftOptions } from "./giftoptions";
import { PackageDimension } from "./packagedimension";
import { PackageWeights } from "./packageweights";
import { TotalWeight } from "./totalweight";
import { Expose, Type } from "class-transformer";

/**
 * A cart that is being prepared for shipment
 */
export class InStoreShipment extends SpeakeasyBase {
    /**
     * The name of the carrier selected.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "carrier" })
    carrier?: string;

    /**
     * The amount. **Nullable** for Transactions Details.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "cost" })
    @Type(() => Amounts)
    cost?: Amounts;

    @SpeakeasyMetadata()
    @Expose({ name: "default" })
    default?: boolean;

    /**
     * The estimated delivery date.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "estimated_delivery_date" })
    estimatedDeliveryDate?: string;

    /**
     * True if shipment is expedited.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "expedited" })
    expedited?: boolean;

    /**
     * Contains the gift option settings for wrapping and custom messages.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "gift_options" })
    @Type(() => GiftOptions)
    giftOptions?: GiftOptions;

    /**
     * ID for billing address
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * Contains the package's width, eight, depth, and unit details.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "package_dimension" })
    @Type(() => PackageDimension)
    packageDimension?: PackageDimension;

    /**
     * The type of package.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "package_type" })
    packageType?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "package_weights" })
    @Type(() => PackageWeights)
    packageWeights?: PackageWeights;

    /**
     * Reference for the object.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "reference" })
    reference?: string;

    /**
     * The service name.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "service" })
    service?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "shipping_address" })
    @Type(() => ConsumerBillingAddress)
    shippingAddress?: ConsumerBillingAddress;

    /**
     * The name of the shipping method.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "shipping_method" })
    shippingMethod?: string;

    /**
     * The signature.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "signature" })
    signature?: string;

    /**
     * The amount. **Nullable** for Transactions Details.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "tax_amount" })
    @Type(() => Amounts)
    taxAmount?: Amounts;

    @SpeakeasyMetadata()
    @Expose({ name: "total_weight" })
    @Type(() => TotalWeight)
    totalWeight?: TotalWeight;
}
