/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ICustomFieldView } from "./icustomfieldview";
import { IGiftOptionView } from "./igiftoptionview";
import { Expose, Type } from "class-transformer";

export enum IOrderDynamicContentEligiblePaymentMethodsTransactionProcessorType {
    Affirm = "affirm",
    Afterpay = "afterpay",
    AmazonPay = "amazon_pay",
    Credova = "credova",
    Klarna = "klarna",
    Paypal = "paypal",
    Sezzle = "sezzle",
    RadialKlarna = "radial_klarna",
    RadialPaypal = "radial_paypal",
    AdyenGateway = "adyen_gateway",
    AllianceData = "alliance_data",
    AuthorizeNet = "authorize_net",
    Braintree = "braintree",
    Cardconnect = "cardconnect",
    CheckoutCom = "checkout_com",
    Cybersource = "cybersource",
    FirstData = "first_data",
    Nmi = "nmi",
    Orbital = "orbital",
    PaypalPayflow = "paypal_payflow",
    Radial = "radial",
    Rocketgate = "rocketgate",
    ShopifyPayments = "shopify_payments",
    Stripe = "stripe",
    Magentopayment = "magentopayment",
    AdyenPayfac = "adyen_payfac",
    Vantiv = "vantiv",
    GooglePay = "google_pay",
    Bolt = "bolt",
}

export class IOrderDynamicContentEligiblePaymentMethods extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "eligible" })
    eligible?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "transaction_processor_type" })
    transactionProcessorType?: IOrderDynamicContentEligiblePaymentMethodsTransactionProcessorType;
}

export enum IOrderDynamicContentHideApm {
    Paypal = "PAYPAL",
    Affirm = "AFFIRM",
    Afterpay = "AFTERPAY",
    Amazonpay = "AMAZONPAY",
    Klarna = "KLARNA",
    Radialpaypal = "RADIALPAYPAL",
    Sezzle = "SEZZLE",
    Radialklarna = "RADIALKLARNA",
    Credova = "CREDOVA",
    Googlepay = "GOOGLEPAY",
}

export class IOrderDynamicContent extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: ICustomFieldView })
    @Expose({ name: "custom_fields" })
    @Type(() => ICustomFieldView)
    customFields?: ICustomFieldView[];

    @SpeakeasyMetadata({ elemType: IOrderDynamicContentEligiblePaymentMethods })
    @Expose({ name: "eligible_payment_methods" })
    @Type(() => IOrderDynamicContentEligiblePaymentMethods)
    eligiblePaymentMethods?: IOrderDynamicContentEligiblePaymentMethods[];

    @SpeakeasyMetadata()
    @Expose({ name: "gift_option_view" })
    @Type(() => IGiftOptionView)
    giftOptionView?: IGiftOptionView;

    @SpeakeasyMetadata()
    @Expose({ name: "hide_apm" })
    hideApm?: IOrderDynamicContentHideApm[];

    @SpeakeasyMetadata()
    @Expose({ name: "order_notice" })
    orderNotice?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "payment_notice" })
    paymentNotice?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "shipping_info_notice" })
    shippingInfoNotice?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "shipping_notice" })
    shippingNotice?: string;
}
