/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum Actions {
    SetPassword = "set_password",
    RotatePassword = "rotate_password",
}

export enum Methods {
    Code = "code",
    CodePassword = "code_password",
    Password = "password",
    RotatePassword = "rotate_password",
}

export class LoginView extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "actions" })
    actions?: Actions[];

    @SpeakeasyMetadata()
    @Expose({ name: "methods" })
    methods?: Methods[];

    @SpeakeasyMetadata()
    @Expose({ name: "sso_authorization_url" })
    ssoAuthorizationUrl?: string;
}
