/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum LoginViewActions {
    SetPassword = "set_password",
    RotatePassword = "rotate_password",
}

export enum LoginViewMethods {
    Code = "code",
    CodePassword = "code_password",
    Password = "password",
    RotatePassword = "rotate_password",
}

export class LoginView extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "actions" })
    actions?: LoginViewActions[];

    @SpeakeasyMetadata()
    @Expose({ name: "methods" })
    methods?: LoginViewMethods[];

    @SpeakeasyMetadata()
    @Expose({ name: "sso_authorization_url" })
    ssoAuthorizationUrl?: string;
}
