/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum ManualDisputesStatus {
    Pending = "pending",
    Approved = "approved",
    Denied = "denied",
}

export class ManualDisputes extends SpeakeasyBase {
    /**
     * The amount in cents. **Nullable** for Transactions Details.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "amount" })
    amount?: number;

    /**
     * The 3-digit ISO code for the currency. **Nullable** for Transactions Details.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "currency" })
    currency?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "delivery_evidence" })
    deliveryEvidence?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "delivery_link" })
    deliveryLink?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "dispute_evidence" })
    disputeEvidence?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "dispute_link" })
    disputeLink?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "other_evidence" })
    otherEvidence?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "other_link" })
    otherLink?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "reason" })
    reason?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: ManualDisputesStatus;
}
