/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class MerchantDivisionLogoView extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "domain" })
    domain?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "resource" })
    resource?: string;
}
