/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { MerchantOnboardingStatusCode } from "./merchantonboardingstatuscode";
import { MerchantStatus } from "./merchantstatus";
import { TransactionOperationalProcessor } from "./transactionoperationalprocessor";
import { TransactionProcessor } from "./transactionprocessor";
import { Expose, Type } from "class-transformer";

export class Merchant extends SpeakeasyBase {
    /**
     * The date the merchant account was created.  **Nullable** for Transactions Details.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "created_at" })
    createdAt: number;

    /**
     * The description of the merchant account. **Nullable** for Transactions Details.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description: string;

    @SpeakeasyMetadata()
    @Expose({ name: "onboarding_status" })
    onboardingStatus?: MerchantOnboardingStatusCode;

    /**
     * **Nullable** for Transactions Details.
     *
     * @remarks
     *
     */
    @SpeakeasyMetadata({ elemType: TransactionOperationalProcessor })
    @Expose({ name: "operational_processors" })
    @Type(() => TransactionOperationalProcessor)
    operationalProcessors: TransactionOperationalProcessor[];

    /**
     * The processor used. **Nullable** for Transactions Details.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "processor" })
    processor: TransactionProcessor;

    /**
     * The unique public ID for the merchant's Bolt account. A merchant account contains many merchant divisions.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "public_id" })
    publicId?: string;

    /**
     * The merchant's status:
     *
     * @remarks
     *   * `1` - Active
     *   * `2` - Inactive
     *   * `3` - Offboarding
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: MerchantStatus;

    /**
     * The timezone of the merchant. **Nullable** for Transactions Details.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "time_zone" })
    timeZone: string;
}
