/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The type of platform being used for this merchant division.
 */
export enum MerchantPlatform {
    None = "none",
    BigCommerce = "big_commerce",
    Shopify = "shopify",
    Magento = "magento",
    Magento2 = "magento2",
    WooCommerce = "woo_commerce",
    Drupal = "drupal",
    Volusion = "volusion",
    Prestashop = "prestashop",
    Netsuite = "netsuite",
    Miva = "miva",
    CommerceCloud = "commerce_cloud",
}
