/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Address } from "./address";
import { CartCreate } from "./cartcreate";
import { ProcessingInitiator } from "./processinginitiator";
import { UserIdentifier } from "./useridentifier";
import { UserIdentity } from "./useridentity";
import { Expose, Type } from "class-transformer";

export enum MerchantCreditCardAuthorizationRechargeSource {
    DirectPayments = "direct_payments",
}

/**
 * This request is used for authorizing an existing, saved card associated with the account.
 */
export class MerchantCreditCardAuthorizationRecharge extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "auto_capture" })
    autoCapture?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "cart" })
    @Type(() => CartCreate)
    cart: CartCreate;

    /**
     * The unique ID associated to the saved credit card in the account's wallet.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "credit_card_id" })
    creditCardId: string;

    /**
     * The unique ID associated to the merchant's Bolt Account division; Merchants can have different divisions to suit multiple use cases (storefronts, pay-by-link, phone order processing). Use the Bolt Merchant Dashboard to switch between divisions and find the division ID under `Merchant Division Public ID`.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "division_id" })
    divisionId: string;

    /**
     * The reference ID associated with a transaction event (auth, capture, refund, void). This is an arbitrary identifier created by the merchant. Bolt does not enforce any uniqueness constraints on this ID. It is up to the merchant to generate identifiers that properly fulfill its needs.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "merchant_event_id" })
    merchantEventId?: string;

    /**
     * The unique ID associated with to the shopper's previous subscription-based transaction. Leave `null` for standard, non-subscription transactions.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "previous_transaction_id" })
    previousTransactionId?: string;

    /**
     * Defines which payment method was used to initiate the transaction.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "processing_initiator" })
    processingInitiator?: ProcessingInitiator;

    /**
     * The Address object is used for billing, shipping, and physical store address use cases.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "shipping_address" })
    @Type(() => Address)
    shippingAddress?: Address;

    @SpeakeasyMetadata()
    @Expose({ name: "source" })
    source: MerchantCreditCardAuthorizationRechargeSource;

    /**
     * The object containing key lookup IDs associated with the shopper's account, such as the unique email address and phone number.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "user_identifier" })
    @Type(() => UserIdentifier)
    userIdentifier: UserIdentifier;

    @SpeakeasyMetadata()
    @Expose({ name: "user_identity" })
    @Type(() => UserIdentity)
    userIdentity: UserIdentity;
}
