/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The merchant's status:
 *
 * @remarks
 *   * `1` - Active
 *   * `2` - Inactive
 *   * `3` - Offboarding
 *
 */
export enum MerchantStatus {
    One = 1,
    Two = 2,
    Three = 3,
}
