/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum MerchantOnboardingStatusCode {
    NewMerchant = "new_merchant",
    UserCreated = "user_created",
    FormFilled = "form_filled",
    IntegrationDone = "integration_done",
    Legacy = "legacy",
    ProcessorSettingsReceived = "processor_settings_received",
}
