/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class MerchantLogo extends SpeakeasyBase {
    /**
     * The URL of the merchant division.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "domain" })
    domain?: string;

    /**
     * The logo image file for the merchant division.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "resource" })
    resource?: string;
}
