/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The status of the shopper account identifier (email or phone). If the account does not have this identifier, the status is "missing"; If the identifier has been used to receive an OTP code, the status is "verified"; If the identifier has not been used to receive an OTP code, the status is "unverified".
 */
export enum Onev11testing1shopper1createPostRequestBodyContentApplication1jsonSchemaPropertiesEmailState {
    Missing = "missing",
    Verified = "verified",
    Unverified = "unverified",
}
