/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { RiskDecisionFactorYml } from "./riskdecisionfactoryml";
import { Expose } from "class-transformer";

/**
 * Decision and score for an order.
 */
export class OrderDecision extends SpeakeasyBase {
    /**
     * The top 5 factors of the fraud decision.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "decision_factors" })
    decisionFactors?: RiskDecisionFactorYml[];

    /**
     * The total fraud risk score of the order.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "score" })
    score?: number;
}
