/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Contains the package's width, eight, depth, and unit details.
 */
export class PackageDimension extends SpeakeasyBase {
    /**
     * The depth.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "depth" })
    depth?: number;

    /**
     * The height.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "height" })
    height?: number;

    /**
     * The unit of measurement for an item's dimensions.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "unit" })
    unit?: string;

    /**
     * The width.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "width" })
    width?: number;
}
