/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class PackageWeights extends SpeakeasyBase {
    /**
     * The unit of measurement for an item's weight.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "unit" })
    unit?: string;

    /**
     * The weight of an item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "weight" })
    weight?: number;
}
