/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { PhonePriority } from "./phonepriority";
import { PhoneStatus } from "./phonestatus";
import { Expose } from "class-transformer";

/**
 * A phone number with country code.
 */
export class PhonesWithCountryCode extends SpeakeasyBase {
    /**
     * A phone number's country code.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "country_code" })
    countryCode?: string;

    /**
     * This is the ID for the phone number associated with the shopper.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * A phone number following E164 standards, in its globalized format, i.e. prepended with a plus sign.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "number" })
    number?: string;

    /**
     * This is the priority of the contact method. This field's contents are not displayed in the transaction details view.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "priority" })
    priority?: PhonePriority;

    /**
     * This is the status of the contact method.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: PhoneStatus;
}
