/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum PhoneViewPriority {
    Primary = "primary",
    Listed = "listed",
}

export class PhoneView extends SpeakeasyBase {
    /**
     * Used for the 2-digit ISO 3166-1 alpha 2 country code associated with this address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "country_code" })
    countryCode?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "number" })
    number?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "priority" })
    priority?: PhoneViewPriority;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: string;
}
