/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * This is the priority of the contact method. This field's contents are not displayed in the transaction details view.
 */
export enum PhonePriority {
    Primary = "primary",
    Listed = "listed",
}
