/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Describes the card's priority.
 *
 * @remarks
 *
 */
export enum Priority {
    Primary = "primary",
    Listed = "listed",
}
