/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Defines which payment method was used to initiate the transaction.
 */
export enum ProcessingInitiator {
    InitialCardOnFile = "initial_card_on_file",
    InitialRecurring = "initial_recurring",
    StoredCardholderInitiated = "stored_cardholder_initiated",
    StoredMerchantInitiated = "stored_merchant_initiated",
    FollowingRecurring = "following_recurring",
    CardholderInitiated = "cardholder_initiated",
    Recurring = "recurring",
}
