/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Custom-defined Bolt result object.
 */
export class RequestResult extends SpeakeasyBase {
    /**
     * Indicates that the request failed. This value is always false.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "success" })
    success?: boolean;
}
