/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { RequestStatus } from "./requeststatus";
import { Expose } from "class-transformer";

/**
 * Internal use only.
 */
export class ReviewTicket extends SpeakeasyBase {
    /**
     * The unique ID for the request ticket.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "request_deadline" })
    requestDeadline?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: RequestStatus;
}
