/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { RiskDecisionFactorYml } from "./riskdecisionfactoryml";
import { Expose } from "class-transformer";

/**
 * Displays fraud decisioning insights based on key factors. This information can either be forwarded via a `risk_insights` transaction webhook type or be polled by sending a `GET` request to Bolt's [transactions endpoint](/api-bolt/#operation/transaction-details).
 *
 * @remarks
 *
 */
export class RiskInsightsYml extends SpeakeasyBase {
    /**
     * Must be set to `true` to receive fraud insights.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "available" })
    available?: boolean;

    /**
     * The top 5 factors of the fraud decision.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "decision_factors" })
    decisionFactors?: RiskDecisionFactorYml[];

    /**
     * The total [fraud score](/merchants/references/policies/fraud-review/#fraud-scoring).
     *
     * @remarks
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "fraud_probability" })
    fraudProbability?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "payment_instrument_factors" })
    paymentInstrumentFactors?: Record<string, string>;
}
