/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class RiskModelExternalResultView extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "available" })
    available?: boolean;

    /**
     * Used to list a total of up to 5 decision factors used by the risk model to determine the risk analysis result.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "decision_factors" })
    decisionFactors?: string[];

    @SpeakeasyMetadata()
    @Expose({ name: "fraud_probability" })
    fraudProbability?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "payment_instrument_factors" })
    paymentInstrumentFactors?: Record<string, string>;
}
