/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { RiskModelResulContributionView } from "./riskmodelresulcontributionview";
import { Expose, Type } from "class-transformer";

export class RiskModelResultView extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: RiskModelResulContributionView })
    @Expose({ name: "contribution" })
    @Type(() => RiskModelResulContributionView)
    contribution?: RiskModelResulContributionView[];
}
