/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Describes the current Risk Review status. A transaction could be unreviewed, reviewed, or pending manual review by the Bolt team.
 */
export enum RiskReviewStatus {
    Unknown = "unknown",
    NeedsReview = "needs_review",
    Reviewed = "reviewed",
}
