/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Metadata } from "./metadata";
import { Expose, Type } from "class-transformer";

/**
 * Type field indicates this is a saved PayPal to differentiate it from a saved card.
 */
export enum SavedPaypalAccountViewType {
    Paypal = "paypal",
}

/**
 * Saved PayPal account details.
 */
export class SavedPaypalAccountView extends SpeakeasyBase {
    /**
     * The email associated with a shopper's saved PayPal account.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description?: string;

    /**
     * The ID of the payment method associated with the Shopper's account.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * A key-value pair object that allows users to store arbitrary information associated with an object.  For any individual account object, we allow up to 50 keys. Keys can be up to 40 characters long and values can be up to 500 characters long.  Metadata should not contain any sensitive customer information, like PII (Personally Identifiable Information). For more information about metadata, see our [documentation](https://help.bolt.com/developers/references/embedded-metadata/).
     *
     * @remarks
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "metadata" })
    @Type(() => Metadata)
    metadata?: Metadata;

    /**
     * Type field indicates this is a saved PayPal to differentiate it from a saved card.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: SavedPaypalAccountViewType;
}
