/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AddressView } from "./addressview";
import { CardNetwork } from "./cardnetwork";
import { Metadata } from "./metadata";
import { Expose, Type } from "class-transformer";

/**
 * The payment method type. If empty, the property defaults to `card`.
 */
export enum SavedCreditCardViewType {
    Card = "card",
    Paypal = "paypal",
}

/**
 * Saved Credit Card Detail
 */
export class SavedCreditCardView extends SpeakeasyBase {
    /**
     * The address object returned in the response.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "billing_address" })
    @Type(() => AddressView)
    billingAddress?: AddressView;

    /**
     * The default card payment method chosen by the shopper.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "default" })
    default?: boolean;

    /**
     * The APM account identifier; usually the email address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description?: string;

    /**
     * The expiration month of the credit card.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "exp_month" })
    expMonth?: number;

    /**
     * The expiration year of the credit card.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "exp_year" })
    expYear?: number;

    /**
     * The ID of the payment method associated with the Shopper's account.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * The card's last 4 digits. **Nullable** for Transactions Details.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "last4" })
    last4?: string;

    /**
     * A key-value pair object that allows users to store arbitrary information associated with an object.  For any individual account object, we allow up to 50 keys. Keys can be up to 40 characters long and values can be up to 500 characters long.  Metadata should not contain any sensitive customer information, like PII (Personally Identifiable Information). For more information about metadata, see our [documentation](https://help.bolt.com/developers/references/embedded-metadata/).
     *
     * @remarks
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "metadata" })
    @Type(() => Metadata)
    metadata?: Metadata;

    /**
     * The card's network code. **Nullable** for Transactions Details. Note: LEGACY diners_club_us_ca now tagged as mastercard
     *
     * @remarks
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "network" })
    network?: CardNetwork;

    /**
     * The payment method type. If empty, the property defaults to `card`.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: SavedCreditCardViewType;
}
