/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

/**
 * The unit for this subscription's frequency.
 */
export enum SubscriptionFrequencyUnit {
    Day = "day",
    Week = "week",
    Month = "month",
    Year = "year",
}

/**
 * Describes how often the subscription recurs.
 */
export class SubscriptionFrequency extends SpeakeasyBase {
    /**
     * The unit for this subscription's frequency.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "unit" })
    unit?: SubscriptionFrequencyUnit;

    /**
     * The value applied to the unit frequency.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "value" })
    value?: number;
}

/**
 * Describes a product added as a recurring subscription.
 */
export class Subscription extends SpeakeasyBase {
    /**
     * Describes how often the subscription recurs.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "frequency" })
    @Type(() => SubscriptionFrequency)
    frequency?: SubscriptionFrequency;
}
