/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Describes whether the transaction is indemnified by Bolt for fraud.
 *
 * @remarks
 *
 */
export enum TransactionIndemnificationDecision {
    Unknown = "unknown",
    Indemnified = "indemnified",
    NotIndemnified = "not_indemnified",
}
