/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The transaction's status.
 */
export enum TransactionStatus {
    InProgress = "in_progress",
    Completed = "completed",
    Cancelled = "cancelled",
    Failed = "failed",
    Pending = "pending",
    Created = "created",
    Authorized = "authorized",
    RejectedReversible = "rejected_reversible",
    RejectedIrreversible = "rejected_irreversible",
}
