/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The type of transaction.
 */
export enum TransactionType {
    CcPayment = "cc_payment",
    CcCredit = "cc_credit",
    FundingTransfer = "funding_transfer",
    ProcessingFeeTransfer = "processing_fee_transfer",
    ReserveTransfer = "reserve_transfer",
    FloatTransfer = "float_transfer",
    MerchantCredit = "merchant_credit",
    MerchantDebit = "merchant_debit",
    FundingWithdrawal = "funding_withdrawal",
    ProcessingFeeWithdrawal = "processing_fee_withdrawal",
    ZeroAmount = "zero_amount",
    BoltFeeTransfer = "bolt_fee_transfer",
    BoltFeeWithdrawal = "bolt_fee_withdrawal",
    BankAccountVerification = "bank_account_verification",
    AuthorizationVerification = "authorization_verification",
    PaypalPayment = "paypal_payment",
    PaypalRefund = "paypal_refund",
    ApmPayment = "apm_payment",
    ApmRefund = "apm_refund",
    ZeroAmountVerification = "zero_amount_verification",
}
