/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { RiskModelResultView } from "./riskmodelresultview";
import { Expose, Type } from "class-transformer";

export class TransactionReviewView extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "date" })
    date?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "decision" })
    decision?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "risk_model_result" })
    @Type(() => RiskModelResultView)
    riskModelResult?: RiskModelResultView;

    @SpeakeasyMetadata()
    @Expose({ name: "source" })
    source?: string;
}
