/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The processor's status. Only `primary` and `active` processor are displayed.
 */
export enum TransactionProcessorStatus {
    Primary = "primary",
    Active = "active",
    Inactive = "inactive",
}
