/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AmountView } from "./amountview";
import { Expose, Type } from "class-transformer";

export enum TransactionSplitsViewType {
    Net = "net",
    ProcessingFee = "processing_fee",
    Float = "float",
    Reserve = "reserve",
    Adjustment = "adjustment",
    BoltFee = "bolt_fee",
}

export class TransactionSplitsView extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "amount" })
    @Type(() => AmountView)
    amount?: AmountView;

    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: TransactionSplitsViewType;
}
