/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * The object containing key lookup IDs associated with the shopper's account, such as the unique email address and phone number.
 */
export class UserIdentifier extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "artifact" })
    artifact?: string;

    /**
     * An email address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "email" })
    email?: string;

    /**
     * The ID associated with the identifying email address for this account.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "email_id" })
    emailId?: string;

    /**
     * A phone number following E164 standards, in its globalized format, i.e. prepended with a plus sign.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "phone" })
    phone: string;

    /**
     * The ID associated with the identifying phone number for this account.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "phone_id" })
    phoneId?: string;
}
