/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * [Webhook events](https://help.bolt.com/developers/guides/webhooks/#transaction-hook-types) that trigger a notification to the URL.  **Note**:`newsletter_subscription` is only for merchant use cases.
 *
 * @remarks
 *
 */
export enum WebhooksType {
    Payment = "payment",
    Credit = "credit",
    Capture = "capture",
    Void = "void",
    Auth = "auth",
    Pending = "pending",
    RejectedIrreversible = "rejected_irreversible",
    RejectedReversible = "rejected_reversible",
    FailedPayment = "failed_payment",
    NewsletterSubscription = "newsletter_subscription",
    RiskInsights = "risk_insights",
    CreditCardDeleted = "credit_card_deleted",
}
