/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../../../sdk/models/shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class UpdatePaymentSecurity extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "security, scheme=true;type=oauth2;name=Authorization" })
    oAuth?: string;

    @SpeakeasyMetadata({ data: "security, scheme=true;type=apiKey;subtype=header;name=X-API-Key" })
    xAPIKey?: string;
}

/**
 * Identification information for the Shopper. This is only required when creating a new Bolt account.
 */
export class UpdatePaymentShopperIdentity extends SpeakeasyBase {
    /**
     * determines whether to create a bolt account for this shopper
     */
    @SpeakeasyMetadata()
    @Expose({ name: "create_bolt_account" })
    createBoltAccount?: boolean;

    /**
     * Email address of the shopper
     */
    @SpeakeasyMetadata()
    @Expose({ name: "email" })
    email: string;

    /**
     * First name of the shopper
     */
    @SpeakeasyMetadata()
    @Expose({ name: "first_name" })
    firstName: string;

    /**
     * Last name of the shopper
     */
    @SpeakeasyMetadata()
    @Expose({ name: "last_name" })
    lastName: string;

    /**
     * Phone number of the shopper
     */
    @SpeakeasyMetadata()
    @Expose({ name: "phone" })
    phone: string;
}

export class UpdatePaymentRequestBody extends SpeakeasyBase {
    /**
     * The details of the cart being purchased with this payment.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "cart" })
    @Type(() => shared.CartCreate)
    cart?: shared.CartCreate;

    /**
     * Identification information for the Shopper. This is only required when creating a new Bolt account.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "shopper_identity" })
    @Type(() => UpdatePaymentShopperIdentity)
    shopperIdentity?: UpdatePaymentShopperIdentity;
}

export class UpdatePaymentRequest extends SpeakeasyBase {
    /**
     * A key created by merchants that ensures `POST` and `PATCH` requests are only performed once. [Read more about Idempotent Requests here](/developers/references/idempotency/).
     */
    @SpeakeasyMetadata({ data: "header, style=simple;explode=false;name=Idempotency-Key" })
    idempotencyKey?: string;

    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    requestBody?: UpdatePaymentRequestBody;

    /**
     * The publicly viewable identifier used to identify a merchant division. This key is found in the Developer > API section of the Bolt Merchant Dashboard [RECOMMENDED].
     */
    @SpeakeasyMetadata({ data: "header, style=simple;explode=false;name=X-Publishable-Key" })
    xPublishableKey?: string;

    /**
     * The ID received in the initial v1/payments request.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=id" })
    id: string;
}

/**
 * The current payment status.
 */
export enum UpdatePaymentStatus {
    AwaitingUserConfirmation = "awaiting_user_confirmation",
    PaymentReady = "payment_ready",
    Success = "success",
}

/**
 * Payment updated.
 */
export class UpdatePaymentResponseBody extends SpeakeasyBase {
    /**
     * The ID for a Payment Attempt
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * The current payment status.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: UpdatePaymentStatus;
}

export class UpdatePaymentResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse: AxiosResponse;

    /**
     * Payment updated.
     */
    @SpeakeasyMetadata()
    object?: UpdatePaymentResponseBody;
}
